### PR TITLE
relative paths

### PR DESCRIPTION
**Pull request by freder**
see #769

### CODE REVIEW

**Comment by outoftime** [comment]
@freder I don’t have any philosophical objection to the changes here, but it looks like they break the development environment—when I run `yarn run dev`, the application doesn’t properly load, and I see these errors:

image

I would have to imagine this is the result of the change in `webpack.config.js`.

**Comment by freder** [comment]
weird, `yarn run dev` still works for me.

**Comment by freder** [comment]
not entirely sure why, but https://github.com/popcodeorg/popcode/pull/770/commits/f4639fb8e2baad741d51f131bbfcb817bda35432 seems to do the trick.

**Comment by outoftime** [comment]
@freder that makes sense—it offsets the change [here](https://github.com/popcodeorg/popcode/pull/770/commits/381f1de1b4a516226696fd817d885e02040b7a44#diff-11e9f7f953edc64ba14b0cc350ae7b9dR41) from BrowserSync’s standpoint

**Pull request merged**
