### PR TITLE
Upgrade yarn to 1.0.1

### PR DESCRIPTION
**Pull request by jwang1919**
New yarn version came out yesterday!

Also updated node to 8.4.0.

### CODE REVIEW

**Comment by outoftime** [comment]
@jwang1919 can you update these in `.travis.yml` as well and see what happens? I fear that Node 8 in particular does cause problems with the build, although that may be an out-of-date concern.

**Comment by jwang1919** [comment]
@outoftime looks good

**Comment by outoftime** [comment]
Thanks! The [yarn version](https://github.com/jwang1919/popcode/blob/429a428a990718e85f16369861e94551a93f8395/.travis.yml#L25) does appear in there as well, though…

**Comment by jwang1919** [comment]
Doh! Didn't catch that one.

**Comment by jwang1919** [comment]
@outoftime okay check now :)

**Comment by outoftime** [comment]
@jwang1919 ah crap it’s merged BUT can you update `.node-version` in another PR?

**Comment by outoftime** [comment]
also looks like yarn 1.0.2 is out?

**Comment by jwang1919** [comment]
@outoftime got it. See: https://github.com/popcodeorg/popcode/pull/1030

**Pull request merged**
