### PR TITLE
WIP: Issues/inline code overlap

### PR DESCRIPTION
**Pull request by omardeleo**
I'd like to implement the following changes in CSS: 
```
.hljs {
  padding: 0 0.2em;
}

.instructions h1, h2, h3, h4, h5, h6 {
  line-height: 1.2;
}
```
but am failing linting, and not sure how to make this compliant. These edits works locally otherwise.
Please see the errors below. Thanks!
screen shot 2018-10-13 at 4 14 03 pm

### CODE REVIEW

**Comment by omardeleo** [comment]
@outoftime Hey Mat, thanks again for your guidance on this. With regards to the `line-height` of the heading, the rule in lines 313-320 is being overwritten (as are the rules nested with SASS ampersand), I just noticed. Even though `line-height` here is set to `1.2 em`, the headers still render with no `line-height`. I added a `color` property to test this and confirmed in the console that it was being overwritten as well. I'll keep trying to figure out a solution, but if you have any thoughts in light of this, I'd love to hear them. 
screen shot 2018-10-16 at 7 19 35 pm
screen shot 2018-10-16 at 7 20 23 pm

**Comment by outoftime** [comment]
@omardeleo ah, you’re running into the bug fixed in [this pull request](https://github.com/popcodeorg/popcode/pull/1585) I think. was hoping to get that PR merged cleanly from a feature branch but may need to help things along since it’s blocking you

**Comment by omardeleo** [comment]
@outoftime Oh ok, everything makes perfect sense now. I'll put this aside for now and start on the other issue I picked up. Please keep me posted, thanks!

**Comment by outoftime** [comment]
@omardeleo can we close this now that the regression with selector nesting is fixed, or are some of these changes still needed?

**Comment by omardeleo** [comment]
Feel free to close!

**Pull request closed without merging**
