### PR TITLE
issue #1573 fixed - images scale to fit width of instructions panel

### PR DESCRIPTION
**Pull request by EricSnell**
added postcss-cssnext to transpile the nested selectors which were being used to style the instructions panel images 👍 

Happy to make any adjustments necessary!

### CODE REVIEW

**Comment by EricSnell** [comment]
```javscript
/* postcss-bem-linter: ignore */
  & li {
    margin-bottom: 0.5em;
  }

  /* postcss-bem-linter: ignore */
  & h1,
  & h2,
  & h3,
  & h4,
  & h5,
  & h6 {
    line-height: 1.2em;
  }

  /* postcss-bem-linter: ignore */
  & img {
    max-width: 100%;
  }
```

**Comment by EricSnell** [comment]
sorry - didn't mean to close!

**Comment by EricSnell** [comment]
fixed! just needed to pass a `features` property to the `postcssPresetEnv` function. Closing and submitting new pull request.

**Comment by EricSnell** [comment]
reopening

**Comment by outoftime** [comment]
@EricSnell I hate to add to the churn with the different pull requests but would you mind opening a pull request with these changes in a feature branch in your fork rather than `master`? Thanks!

**Comment by EricSnell** [comment]
My appologies -- I'll open a new branch

**Comment by outoftime** [comment]
Closed by #1591

**Pull request closed without merging**
