### PR TITLE
Experiment with Rollup for building assets

### PR DESCRIPTION
**Pull request by wilsonj806**
# General Notes
Some general notes while I was messing with Rollup:
- As an initial report, Rollup JS bundle size is about the same as Webpack(just getting file sizes from `du -sh`
- Rollup's build takes 2 minutes to build over 5 minutes with Webpack on my Macbook
  - just have the bare minimum plugins for the Rollup config so that could be explain part of why it's so fast as of 7/3/2020
- Requires you to specify local CommonJS files in the Rollup config file

Added some [process notes](https://github.com/wilsonj806/popcode/blob/TEST/rollup-experiments/branch-notes/rollup-things.md) as well.

# General Questions
- I have no clue what `locales/index.js` is for even though it's imported by `src/init/initl8n.js`

Relates to #1888

### CODE REVIEW

**Comment by outoftime** [comment]
Thanks for the great writeup @wilsonj806! 

> As an initial report, Rollup JS bundle size is about the same as Webpack

Do you think this is dispositive? Any reason to think we could tweak the Rollup configuration to get more size efficiency out of tree shaking? If we think this result will hold, then I would say we are pretty much done here—a worthwhile experiment to be sure, but if there is no improvement to bundle size, Iʼm inclined to stick with Webpack given its richer ecosystem, fact that we have a working Webpack implementation already, etc. Thoughts?

**Comment by wilsonj806** [comment]
@outoftime No problem! And yeah, at a glance it doesn't seem worthwhile to continue to mess with Rollup when there's a working Webpack config already.

**Comment by outoftime** [comment]
Ten four, thanks for the investigation @wilsonj806 . Even though we’re not going to move forward it’s quite useful to have ruled out a switch to Rollup as an avenue for for bundle size optimization. I’m going to go ahead and close #1888 and you’re welcome to do the same here. 

Let me know if you’re interested in picking up another Popcode project—happy to help find one that fits your interests 🙂

**Comment by wilsonj806** [comment]
@outoftime Yeah that'd be cool! I'm mostly interested in getting better at React/ Redux right now, so if you have anything related to that, I'd be down for it.

**Comment by outoftime** [comment]
Heyo! Definitely lots of projects that will have you deep in React/Redux territory. A couple questions so I can calibrate my suggestions:

- How much React experience do you have now? How much experience with Redux?
- How big a project are you looking to take on? The most impactful projects will be on the bigger side, generally involving multiple pull requests, a planning phase before coding starts, etc. But we have more bite-sized work to be done as well if thatʼs your preference.

Let me know!

**Comment by wilsonj806** [comment]
Re your questions:
- React experience-wise it's about a year or so, and more specifically, I feel comfortable enough with the React workflow that I can pickup things on the go
- Redux-wise I'm not nearly as comfortable, I know the basic patterns and have used Redux Thunk but haven't used Sagas as you guys are using. I'm open to learning it though
- Project size, I think I want to tackle something a bit more bit-sized to start with!

**Comment by outoftime** [comment]
Nice @wilsonj806! Want to join us on https://slack.popcode.org to continue the discussion? I have one or two ideas that I think could be a good fit.

**Pull request closed without merging**
