### PR TITLE
Directly import svg icons

### PR DESCRIPTION
**Pull request by razzius**
https://github.com/popcodeorg/popcode/issues/1574

Before this change
image

After this change
image

### CODE REVIEW

**Comment by razzius** [comment]
Strangely the gzip size is higher after directly importing the icons...

**Comment by outoftime** [comment]
> Strangely the gzip size is higher after directly importing the icons...

Weird, any theories as to why? Have you taken a look at the bundle profiles before/after?

**Comment by razzius** [comment]
Maybe it has something to do with the gzip algorithm; by pulling in multiple modules separately, the similarity of each svg is not as easily identifiable as compressible. I can take a look at the profiles and see if anything obvious comes to light but it's not something I'm super familiar with.

**Comment by outoftime** [comment]
Hey @razzius did you get a chance to look at the profiles?

**Comment by razzius** [comment]
No, haven't taken another look, and I'm not sure what I could look at beyond the screenshots above. Any ideas?

**Comment by outoftime** [comment]
@razzius OK I think I know what’s going on—the `free-solid-svg-icons` package has an `index.es.js` package that does ES exports, which is properly configured as the `module` entrypoint in its `package.json`; apparently that’s enough for Webpack to tree-shake out the icons we don’t import. I have confirmed this by grepping the compiled production JS bundle for the SVG paths of icons we do and don’t use—the ones we do use appear in the bundle, but the ones we don’t use don’t.

So, I think probably the current approach is preferable—I’m guessing it’s slightly smaller because there is a little extra boilerplate for each imported module, and `index.es.js` inlines all the icons. It’s also a bit more concise to just do named imports out of the index module. So I am going to close this—sorry for wasting your time with my incomplete understanding of the way the existing imports were working!!

**Pull request closed without merging**
